name: Azure VM Deployment and .Net App Setup
 
on:
  workflow_dispatch:
 
jobs:
  Deploy:
    runs-on: self-hosted
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3
 
      # Step 2: Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
 
      - name: Deploy Bicep file
        uses: azure/arm-deploy@v1
        id: deploy
        with:
          scope: resourcegroup
          resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
          template: ./azure/main.bicep
          parameters: ./azure/parameters.json
          failOnStdErr: false
 
      - name: Get Outputs
        run: echo " ${{ steps.deploy.outputs.sshCommand }}"
